2024-12-28 10:36:06,594 INFO    MainThread:228415 [wandb_setup.py:_flush():68] Current SDK version is 0.19.1
2024-12-28 10:36:06,594 INFO    MainThread:228415 [wandb_setup.py:_flush():68] Configure stats pid to 228415
2024-12-28 10:36:06,594 INFO    MainThread:228415 [wandb_setup.py:_flush():68] Loading settings from /home/harlab/.config/wandb/settings
2024-12-28 10:36:06,594 INFO    MainThread:228415 [wandb_setup.py:_flush():68] Loading settings from /home/harlab/1-ncsu/mass-dart-exo/python/wandb/settings
2024-12-28 10:36:06,594 INFO    MainThread:228415 [wandb_setup.py:_flush():68] Loading settings from environment variables
2024-12-28 10:36:06,595 INFO    MainThread:228415 [wandb_init.py:_log_setup():528] Logging user logs to /home/harlab/1-ncsu/mass-dart-exo/python/wandb/run-20241228_103606-vlj5e9da/logs/debug.log
2024-12-28 10:36:06,595 INFO    MainThread:228415 [wandb_init.py:_log_setup():529] Logging internal logs to /home/harlab/1-ncsu/mass-dart-exo/python/wandb/run-20241228_103606-vlj5e9da/logs/debug-internal.log
2024-12-28 10:36:06,595 INFO    MainThread:228415 [wandb_init.py:init():644] calling init triggers
2024-12-28 10:36:06,595 INFO    MainThread:228415 [wandb_init.py:init():650] wandb.init called with sweep_config: {}
config: {}
2024-12-28 10:36:06,595 INFO    MainThread:228415 [wandb_init.py:init():680] starting backend
2024-12-28 10:36:06,595 INFO    MainThread:228415 [wandb_init.py:init():684] sending inform_init request
2024-12-28 10:36:06,624 INFO    MainThread:228415 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-12-28 10:36:06,624 INFO    MainThread:228415 [wandb_init.py:init():697] backend started and connected
2024-12-28 10:36:06,625 INFO    MainThread:228415 [wandb_init.py:init():790] updated telemetry
2024-12-28 10:36:06,631 WARNING MsgRouterThr:228415 [router.py:message_loop():75] message_loop has been closed
2024-12-28 10:36:06,635 INFO    MainThread:228415 [wandb_init.py:init():822] communicating run to backend with 90.0 second timeout
2024-12-28 10:36:11,639 ERROR   MainThread:228415 [wandb_init.py:init():1308] error in wandb.init()
Traceback (most recent call last):
  File "/home/harlab/anaconda3/envs/exo/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1298, in init
    return wi.init()
  File "/home/harlab/anaconda3/envs/exo/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 825, in init
    result = run_init_handle.wait(
  File "/home/harlab/anaconda3/envs/exo/lib/python3.8/site-packages/wandb/sdk/lib/mailbox.py", line 277, in wait
    raise MailboxError("transport failed")
wandb.sdk.lib.mailbox.MailboxError: transport failed
